name = input('Enter Your Name : ')
roll_number = input('Enter Your Roll Number : ')
_max_math = input('Enter Maximum Marks of Mathematics : ')
_obt_math = input('Enter Obtained Marks : ')
_max_english = input('Enter Maximum Marks of English : ')
_obt_english = input('Enter Obtained Marks : ')
_max_urdu = input('Enter Maximum Marks of Urdu : ')
_obt_urdu = input('Enter Obtained Marks : ')
_max_physics = input('Enter Maximum Marks of Physics : ')
_obt_physics = input('Enter Obtained Marks : ')
_max_chemistry = input('Enter Maximum Marks of Chemistry : ')
_obt_chemistry = input('Enter Obtained Marks : ')
_max_biology = input('Enter Maximum Marks of Biology : ')
_obt_biology = input('Enter Obtained Marks : ')

_max_marks = int(_max_math) + int(_max_english) + int(_max_urdu) + int(_max_physics) + int(_max_biology) + int(_max_chemistry)
_obtained_marks = int(_obt_math) + int(_obt_english) + int(_obt_urdu) + int(_obt_physics) + int(_obt_biology) + int(_obt_chemistry)
_obtained_percentage = (_obtained_marks / _max_marks) * 100

print('-----------------------------------------------------------------------------------')
print('*********************************** MARKS SHEET ***********************************')
print('-----------------------------------------------------------------------------------')
print('******************************* RESULT OF FINAL EXAM ******************************')
print('-----------------------------------------------------------------------------------')
print('**** FULL NAME     : ' + name + '                                                  ')
print('**** ROLL NUMBER   : ' + roll_number + '                                           ')
print('-----------------------------------------------------------------------------------')
print('**** S.# **** SUBJECTS ********************* TOTAL MARKS ****** OBTAINED MARKS ****')
print('-----------------------------------------------------------------------------------')
print('     '+ '01.        '+'MATHEMATICS'+'                     '+_max_math +'                 '+ _obt_math)
print('     '+ '02.        '+'ENGLISH'+'                         '+_max_english +'                 '+ _obt_english)
print('     '+ '03.        '+'URDU'+'                            '+_max_urdu +'                 '+ _obt_urdu)
print('     '+ '04.        '+'PHYSICS'+'                         '+_max_physics +'                 '+ _obt_physics)
print('     '+ '05.        '+'CHEMISTRY'+'                       '+_max_chemistry +'                 '+ _obt_chemistry)
print('     '+ '06.        '+'BIOLOGY'+'                         '+_max_biology +'                 '+ _obt_biology)
print('-----------------------------------------------------------------------------------')
print('                '+'TOTALS'+'                          '+str(_max_marks) +'                 '+ str(_obtained_marks))
print('-----------------------------------------------------------------------------------')
print('                '+'OBTAINED PERCENTAGE'+'             '+str(_obtained_percentage))
print('-----------------------------------------------------------------------------------')